export const LineID = {
    line1: "line-1",
    line2: "line-2",
    line3: "line-3",
    line4: "line-4",
    line5: "line-5",
    line6: "line-6",
    line7: "line-7",
    line8: "line-8",
    line9: "line-9",
    lineAir: "line-air",
    lineGyeongui: "line-gyeongui",
    lineUisinsul: "line-uisinsul",
    lineGyeongang: "line-gyeongang",
    lineGyeonchun: "line-gyeonchun",
    lineSinrim: "line-sinrim",
    lineEver: "line-ever",
    lineIncheon1: "line-incheon1",
    lineSeohae: "line-seohae",
    lineGimpo: "line-gimpo",
    lineSinbundang: "line-sinbundang",
    lineIncheon2: "line-incheon2",
    lineSuinbundang: "line-suinbundang",
    lineUijeongbu: "line-uijeongbu",
};
export const HexLineColor = {
    "line-1": "#0052A4",
    "line-2": "#00A84D",
    "line-3": "#EF7C1C",
    "line-4": "#00A5DE",
    "line-5": "#996CAC",
    "line-6": "#CD7C2F",
    "line-7": "#747F00",
    "line-8": "#E6186C",
    "line-9": "#BDB092",
    "line-air": "#0090D2",
    "line-gyeongui": "#77C4A3",
    "line-uisinsul": "#B0CE18", // Corrected typo from BOCE18 to B0CE18
    "line-gyeongang": "#003DA5",
    "line-gyeonchun": "#0C8E72",
    "line-sinrim": "#6789CA",
    "line-ever": "#6FB245",
    "line-incheon1": "#7CA8D5",
    "line-seohae": "#81A914",
    "line-gimpo": "#A17800",
    "line-sinbundang": "#D4003B",
    "line-incheon2": "#ED8B00",
    "line-suinbundang": "#F5A200",
    "line-uijeongbu": "#FDA600",
};
export const LineKorean = {
    "line-1": "1호선",
    "line-2": "2호선",
    "line-3": "3호선",
    "line-4": "4호선",
    "line-5": "5호선",
    "line-6": "6호선",
    "line-7": "7호선",
    "line-8": "8호선",
    "line-9": "9호선",
    "line-air": "공항철도",
    "line-gyeongui": "경의중앙선",
    "line-uisinsul": "우이신설",
    "line-gyeongang": "경강선",
    "line-gyeonchun": "경춘선",
    "line-sinrim": "신림선",
    "line-ever": "용인에버라인",
    "line-incheon1": "인천1호선",
    "line-seohae": "서해선",
    "line-gimpo": "김포골드라인",
    "line-sinbundang": "신분당선",
    "line-incheon2": "인천2호선",
    "line-suinbundang": "수인분당선",
    "line-uijeongbu": "의정부경전철",
};


