export const LineID = {
    line1: "LINE_1",
    line2: "LINE_2",
    line3: "LINE_3",
    line4: "LINE_4",
    line5: "LINE_5",
    line6: "LINE_6",
    line7: "LINE_7",
    line8: "LINE_8",
    line9: "LINE_9",
    lineAir: "LINE_AIR",
    lineGyeongui: "LINE_GYEONGUI",
    lineUisinsul: "LINE_UISINSUL",
    lineGyeongang: "LINE_GYEONGANG",
    lineGyeonchun: "LINE_GYEONCHUN",
    lineSinrim: "LINE_SINRIM",
    lineEver: "LINE_EVER",
    lineIncheon1: "LINE_INCHEON1",
    lineSeohae: "LINE_SEOHEA",
    lineGimpo: "LINE_GIMPO",
    lineSinbundang: "LINE_SINBUNDANG",
    lineIncheon2: "LINE_INCHEON2",
    lineSuinbundang: "LINE_SUINBUNDANG",
    lineUijeongbu: "LINE_UIJEONGBU",
};

export const HexLineColor = {
    "LINE_1": "#0052A4",
    "LINE_2": "#00A84D",
    "LINE_3": "#EF7C1C",
    "LINE_4": "#00A5DE",
    "LINE_5": "#996CAC",
    "LINE_6": "#CD7C2F",
    "LINE_7": "#747F00",
    "LINE_8": "#E6186C",
    "LINE_9": "#BDB092",
    "LINE_AIR": "#0090D2",
    "LINE_GYEONGUI": "#77C4A3",
    "LINE_UISINSUL": "#B0CE18",
    "LINE_GYEONGANG": "#003DA5",
    "LINE_GYEONCHUN": "#0C8E72",
    "LINE_SINRIM": "#6789CA",
    "LINE_EVER": "#6FB245",
    "LINE_INCHEON1": "#7CA8D5",
    "LINE_SEOHEA": "#81A914",
    "LINE_GIMPO": "#A17800",
    "LINE_SINBUNDANG": "#D4003B",
    "LINE_INCHEON2": "#ED8B00",
    "LINE_SUINBUNDANG": "#F5A200",
    "LINE_UIJEONGBU": "#FDA600",
};

export const LineKorean = {
    "LINE_1": "1호선",
    "LINE_2": "2호선",
    "LINE_3": "3호선",
    "LINE_4": "4호선",
    "LINE_5": "5호선",
    "LINE_6": "6호선",
    "LINE_7": "7호선",
    "LINE_8": "8호선",
    "LINE_9": "9호선",
    "LINE_AIR": "공항철도",
    "LINE_GYEONGUI": "경의중앙선",
    "LINE_UISINSUL": "우이신설",
    "LINE_GYEONGANG": "경강선",
    "LINE_GYEONCHUN": "경춘선",
    "LINE_SINRIM": "신림선",
    "LINE_EVER": "용인에버라인",
    "LINE_INCHEON1": "인천1호선",
    "LINE_SEOHEA": "서해선",
    "LINE_GIMPO": "김포골드라인",
    "LINE_SINBUNDANG": "신분당선",
    "LINE_INCHEON2": "인천2호선",
    "LINE_SUINBUNDANG": "수인분당선",
    "LINE_UIJEONGBU": "의정부경전철",
};